---

- hosts: localhost

  collections:
  - kubernetes.core

  tasks:

  - name: dependancy
    shell: "pip3 install openshift pyyaml kubernetes; ansible-galaxy collection install kubernetes.core"

  - name: create k8s pod
    kubernetes.core.k8s:
      src: deployment.yaml
      namespace: default
      state: present
