apiVersion: apps/v1
kind: Deployment
metadata:
  name: racing-game
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: racing-game
  template:
    metadata:
      labels:
        app: racing-game
    spec:
      containers:
      - name: racing-game
        image: quay.io/openshifttest/nginx-alpine:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
