---

- hosts: localhost

  collections:
  - kubernetes.core

  tasks:

  - name: dependancy
    shell: "pip3 install openshift pyyaml kubernetes; ansible-galaxy collection install kubernetes.core"


  - name: Get a list of all pods from any namespace
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: prod-game-app
    register: pod_list